// <auto-generated />
using System;
using Learninator.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Learninator.Migrations
{
    [DbContext(typeof(LearninatorContext))]
    [Migration("20191010075034_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Learninator.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Learninator.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LinkId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Learninator.Models.Tag", b =>
                {
                    b.HasOne("Learninator.Models.Link")
                        .WithMany("Tags")
                        .HasForeignKey("LinkId");
                });
#pragma warning restore 612, 618
        }
    }
}
